language: python
stages:
  - lint
  - test
  - deploy
python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  global:
    - THIS_REPO="${TRAVIS_REPO_SLUG#*/}"
    - OWNER=YakDriver
    - RELEASE_VERSION=$(grep -E '^current_version' $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //')
    - PRIOR_VERSION=$(git describe --abbrev=0 --tags)

stage: test
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
install:
  - pip install -r requirements/pip.txt
  - pip install -r requirements/test.txt
  - pip install --editable .
script:
  - pytest
jobs:
  include:
    - stage: lint
      python: 3.6
      install:
        - pip install -r requirements/pip.txt
        - pip install -r requirements/lint.txt
        - pip install --editable .
      script:
        - pylint oschmod
        - pylint tests/*py
        - flake8
    - stage: deploy
      python: 3.6
      env:
        - JOB="Deploy to PyPI"
      install: skip
      script:
        - |
          if [ "$TRAVIS_TAG" = "" ]; then
            ver=$(git show -s --format=%cd --date=format:'%Y%m%d%H%M%S')
            sed -i -E "s/^(version = )([0-9]+\.[0-9]+\.[0-9]+).*$/\1\2.dev$ver/" setup.cfg
          fi
      deploy:
        - provider: pypi
          server: https://test.pypi.org/legacy/
          distributions: sdist bdist_wheel
          user: __token__
          password:
            secure: "m3K/C6HINvSihnKJvkZ/ue2f+RqBhRIuZjkN8gbWcs+GpOdPazA0FMDjAz7sAzh5+n3ChKvNeA1VzEZQ2x6qNLi8xMdp+J1evC5RA7ag/lZ8F5YVvzz4XRsyAjxmIDvtM3K+6C49U7fP7+TmDk6h6+DDIIVYkU0O6eZhxqttuoqOs5xrUhKcKhnt8tt4kU//zaU6OLVuPQ5MdMCPTc9Fi9LQefXh0ZGYd2JafkxdsmyPySLcJwSeOs0k/31UIcuX1tspMCsD9RrXAFQqbdOohUl2iS+NdB/T1Ph09/XmMk06KmAaut5cA9RBxAYBH9GKF0QdhBQC0QZVe54/eyWfmXRUhTuXy4X2EXq2cPS1AJhf0b8HOgFruGqHtb2IiL2iCfw21NojGHp77BtFegsFBYDwIwcN6Vj0Kk99madwliUwY2pIhcj/4uYLw6qqX8r13dBHyElrD2zjOPcFXlYMo4YygI7qyaL4V+HIWl133Sq6oJVzz0U1pP93VOq2Lj4HSrLrqugIxjIwvfiKMFgiLxHVvioSMOTRwuo60YKMivZGcHXiW4OpPijAxNqpyte6zK9y1+P8FAXwfe/sS7KsZPfSuTT9YiPvKqchZYZLLI0RnYoDxvn4M1ZDxQSt5IATnGgA54Sva1fV3x2u5TUBvxZkZcV1ah1NaPC8mZyMmaw="
          skip_cleanup: true
          skip_upload_docs: true
          on:
            branch: master
        - provider: pypi
          distributions: sdist bdist_wheel
          user: __token__
          password:
            secure: "bCxmyUGMybtgQPJufwT0A5Y/dQrqRzuCMRfsTLKDJRVldgnu6sP07MdpXqQcjyMxNCPJu8PWMddm3ydwj6hS7ID3ntP7ADUPdUAyl0IwVKdCqAjQlI+EdNhYnHtBXyOSuju6Nl4u9gjtNfzsedkqp/03KsN2PZDIgjoyg0b4Rs+JxFgsCzAtzMiJhv9C33kMOKE4goZik3K5RJ8bfxsvrvt38vAS+l2GAyw4A5ur9LqD9/b6NzoZdheP2/dqnlBkycw+cpk0BXx9S6apRMfhlRxv28u992LeA2XYeWvgifEzP8kYdme/vAhzLMkqCdBGPpkOKtmSLLHTuDKt18AIwsH0FxPUUm6mO5Uhpl76d/d8SVxHXI9IvG/jn2hI5kPhtZ1fQ/JMLo7FHoN/ZtdIUe2ffiFT+ialw0WYlDSj3JeODxd2SeN/QGM9FJ0f57QYzXNkmTpXhcc6qQ7aKh1J7NZn6mIm8xYdBnRqm/c1T9nAsfG3Bzk/7GqTs2IUUQPfS0PNc7XcSDA3KIXwQta3yY28MtOFBnh7dWzOOC0tleyngulJGAXKJVD+MiS+MtAwlU8IWlYqYufsXbV5c5+UcMR2L6WThRDT4YfIRvtiLILyaWrmAk0mzoeqGQ0lLUonYDkIk/f630nWAt2wifg8oxVLRQV/fgjdW+UqnqcI2v4="
          skip_upload_docs: true
          on:
            tags: true
    - stage: deploy
      if: branch = master AND tag IS blank
      python: 3.6
      install: skip
      script:
        - export RELEASE_BODY="* [$THIS_REPO v$RELEASE_VERSION CHANGELOG](https://github.com/$OWNER/$THIS_REPO/compare/$PRIOR_VERSION...$RELEASE_VERSION)"
        - echo RELEASE_BODY=$RELEASE_BODY
        - env
        - echo PRIOR_VERSION=$PRIOR_VERSION
        - echo RELEASE_VERSION=$RELEASE_VERSION
      deploy:
        - provider: releases
          name: $RELEASE_VERSION
          tag_name: $RELEASE_VERSION
          target_commitish: $TRAVIS_COMMIT
          body: $RELEASE_BODY
          draft: false
          skip_cleanup: true
          api_key:
            secure: "kyYnz7InDJU8azI3iCl57RqqJpNbbe7Z51jp8mFFgG5NU6HSEwQLkwVJMOyJMxn0jVPQ710usJsYGTxpf++UUc9W/38lWqBlEvav8YN9OsrBukD6e1iClRZ5L1mXEGx8g05d+Fop0hhMbzmP6Bd6iSQSuqq4ThRk205Fimqg20VhR1xr17xVXj+0V4JZ4v9tjw6LnbU5yRvf56/MZ2iucQOnVPJz/ut7TyHrbHio4KJnK+eKIUhC541QCAuVglVNmhqYEby73gSXoqFrPOaitDEuQ/OCJSx0+p6ehmSvrZPHDZKE5kbBrm5HndIuUQAblsOMXO/4P+fe33FFeN7W/82Yt2wLfNT+Fgvf5URbj76xVHsaHcGvGsSZGUqYBa0ybd8wBsCTlbltN+BGhOCvdUbneA1nZTqKfj0Nnsw3K+yfe+Ho/nvPXpXlKP7PUuRA1U9SYT22jq6zEepluPAKf6N0V+scS+k3C7AfagKa5+/po1jm5tE47ZIhBvFrgj1RLhnlKmHxYs7GvCKqaE1oUo0rp6p2ZviXvf6oNMP95Gd4zTZt2C5dA20AS99YKEmtbOEuydeBBJNGdICnykzC8VfmYXDLeOmJuFNgEN3OnOF6iw6DawdAHtfbHI3TR7Iy3iTtiQ7mUQnpG8j9NvQo1Vx6FfLfhZVqTYVoV/kUHAA="
          on:
            branch: master
            condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
