language: python
stages:
  - lint
  - test
  - deploy
python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  global:
    - THIS_REPO="${TRAVIS_REPO_SLUG#*/}"
    - OWNER=YakDriver
    - RELEASE_VERSION=$(grep -E '^current_version' $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //')
    - PRIOR_VERSION=$(git describe --abbrev=0 --tags)

stage: test
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
install:
  - pip install -r requirements/pip.txt
  - pip install -r requirements/test.txt
  - pip install --editable .
script:
  - pytest
jobs:
  include:
    - stage: lint
      python: 3.6
      install:
        - pip install -r requirements/pip.txt
        - pip install -r requirements/lint.txt
        - pip install --editable .
      script:
        - pylint oschmod
        - pylint tests/*py
        - flake8
    - stage: deploy
      python: 3.6
      env:
        - JOB="Deploy to PyPI"
      install: skip
      script:
        - |
          if [ "$TRAVIS_TAG" = "" ]; then
            ver=$(git show -s --format=%cd --date=format:'%Y%m%d%H%M%S')
            sed -i -E "s/^(version = )([0-9]+\.[0-9]+\.[0-9]+).*$/\1\2.dev$ver/" setup.cfg
          fi
      deploy:
        - provider: pypi
          server: https://test.pypi.org/legacy/
          distributions: sdist bdist_wheel
          user: __token__
          password:
            secure: "A4ojOGRNri2bIpUlb6eVzZ/+okliLCSvzNCldINewd8CrsWK41iEhFsoM2dhY3cgdh2AGwZkFTdkrHrU37MS+etszpYZ+T2opc9UXQlSHkMWhDtMfUOIV8VTopGX1oHntqS5htUEO6aF7OeG7g72kkU29hPUFVM0XqEMOxxL2t8v7Ce6I55i4la9RFsmOpvnf9mExA9CLrrPNOECZQT7TPe28fGplrZ3OK7U+KBEyFDt0F9eZuzJgdPtaMGpJGXAtsW2gkA86wVF9t2hl95Z+IT5gCttBFDfBSYKO728Ht/43g8EGyktm3X6bQT4fkoKpBPubpYlbjRvsF3vxptBB4EGzKGh5OXJ8oY5QlU4AqSWeZeNxehxWtnGTDbdx3g9jmR1tzxPndoBvupTLw366BvQZQ0Ox/UGad0dHKiRHabwA5nZfZ8C9MYtzHpyenfOzEAtE2XQnhuImZD5h42CdDER0vIea1PvPFiE/PmvO/5s6Yf/sMY8AT+hCz98acUQ5yd2Iw3pCfdyhuwp9b/WAXd1l2nKyJstb57ZU1vUcONhNoNPNb9qZPygBWqZk6bTtORV7aLIDvMKM9Vbay0DPmx5ctAhCogJj8X+TJF0q100AEZiRsZBkbrW/YqTf1OD7XjmTxtQY63/BHFVP3XrDfDZwCE3HwkOSO6ccTikBlc="
          skip_cleanup: true
          skip_upload_docs: true
          on:
            branch: master
        - provider: pypi
          distributions: sdist bdist_wheel
          user: __token__
          password:
            secure: "qIiNdoXA5mIE15IY9eM/ofVACUETgDeI5QysmmBVFd+xWW4jaJHwoOjsPg4Z9yu+gSHpX6Cwyd30eLiK0sOT6lUu7AJCfK1uAteDZWMsGLe0izzlBVWo0dRDavoVPwBM1Bh3XFrc4iwG3u783tmgOOChbht4NTvFyjlylscgB89RCaiFLSp9Ax1ZNqAEJyNtjFrsdRrjUSzof2JxGWXUGwTQkBYRTb9ZzU0cBRspw+OhxbruK52Htr6ncanUzXWYT1ocTVaiAtnkC1Pl6IGZWzQ0r7nASZH046K/O+eu1edffPDQEN8roWnh8UfrAtiRNskrc14pbD9mOZGHYwwLdMALXIGkhxJMlnMEJ1ohakmm8GLQMAejnPrt/lBbAbTBw41MLKPiDV3YWs2mAFwbtCCqB6mseZvF7SNJfUOjfKWMIWDo/RzPHDWB4WBSqbroFJghyjbYsXSgMw4C9KKSNW9UPzKlZFLXasgJbVUMyUIwe8Z9UFZN+MGNZIsi/AX9mtVNd2bol8gHEZ+d+LYc473+Ln6be4uD6BXeQx4VlkvLYWGx+qvkUdw8nMZ2sOmP5h0urzN6Zet9M7B9gcVsiYzu/erzHX/xT+IQmwdvsjdI/wJ/ZV4TbhHnCr0z1BrQzZDXmIvjxuSm1FmQbVpqhznx3WFuIXajd9eg6qyUnQ4="
          skip_upload_docs: true
          on:
            tags: true
    - stage: deploy
      if: branch = master AND tag IS blank
      python: 3.6
      install: skip
      script:
        - export RELEASE_BODY="* [$THIS_REPO v$RELEASE_VERSION CHANGELOG](https://github.com/$OWNER/$THIS_REPO/compare/$PRIOR_VERSION...$RELEASE_VERSION)"
        - echo RELEASE_BODY=$RELEASE_BODY
        - env
        - echo PRIOR_VERSION=$PRIOR_VERSION
        - echo RELEASE_VERSION=$RELEASE_VERSION
      deploy:
        - provider: releases
          name: $RELEASE_VERSION
          tag_name: $RELEASE_VERSION
          target_commitish: $TRAVIS_COMMIT
          body: $RELEASE_BODY
          draft: false
          skip_cleanup: true
          api_key:
            secure: "kyYnz7InDJU8azI3iCl57RqqJpNbbe7Z51jp8mFFgG5NU6HSEwQLkwVJMOyJMxn0jVPQ710usJsYGTxpf++UUc9W/38lWqBlEvav8YN9OsrBukD6e1iClRZ5L1mXEGx8g05d+Fop0hhMbzmP6Bd6iSQSuqq4ThRk205Fimqg20VhR1xr17xVXj+0V4JZ4v9tjw6LnbU5yRvf56/MZ2iucQOnVPJz/ut7TyHrbHio4KJnK+eKIUhC541QCAuVglVNmhqYEby73gSXoqFrPOaitDEuQ/OCJSx0+p6ehmSvrZPHDZKE5kbBrm5HndIuUQAblsOMXO/4P+fe33FFeN7W/82Yt2wLfNT+Fgvf5URbj76xVHsaHcGvGsSZGUqYBa0ybd8wBsCTlbltN+BGhOCvdUbneA1nZTqKfj0Nnsw3K+yfe+Ho/nvPXpXlKP7PUuRA1U9SYT22jq6zEepluPAKf6N0V+scS+k3C7AfagKa5+/po1jm5tE47ZIhBvFrgj1RLhnlKmHxYs7GvCKqaE1oUo0rp6p2ZviXvf6oNMP95Gd4zTZt2C5dA20AS99YKEmtbOEuydeBBJNGdICnykzC8VfmYXDLeOmJuFNgEN3OnOF6iw6DawdAHtfbHI3TR7Iy3iTtiQ7mUQnpG8j9NvQo1Vx6FfLfhZVqTYVoV/kUHAA="
          on:
            branch: master
            condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
